fly/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^editing/$', views.editing, name="editing"),
    url(r'^lncrna/$', views.lncrna, name="lncrna"),
    url(r'^mirna/$', views.mirna, name="mirna"),
    url(r'^download/$', views.download, name="download"),
    url(r'^help/$', views.help, name="help"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^queryset/(?P<page>\w*.*\w*)/$', views.getQuerySet, name="queryset"),

    #Editing details
    url(r'^editing/show/(?P<editingid>\d*)/$', views.editingShow, name="editingshow"),

    #lncRNA detail
    # url(r'^lncrna/(?P<chrom>chr[1-9|XYM][0-9]?)/$', views.lncrnaChr, name="lncrnachr"),
    url(r'^lncrna_chr/$', views.lncrnaChr, name="lncrnachr"),
    url(r'^lncrna/show/(?P<lncrnaid>\d*)/$', views.lncrnaShow, name="lncrnashow"),
    url(r'^lncrna/sequence/(?P<lncrnaid>\d*)/$', views.sequence, name='lncrnasequence'),
    url(r'^lncrna/structure/lncrnastructure_(?P<lncrnaid>\d*).png/$', views.lncrnaStructure, name="lncrnastructure"),

    # miRNA details
    url(r'^mirna/expression/$', views.mirnaExpression, name='mirnaexpression'),
    url(r'^mirna/show/(?P<mirnaid>\d*)/$', views.mirnaShow, name="mirnashow"),

    #funciton gain and loss
    # funciton gain and loss
    url(r'^function/(?P<function>gain|loss)/(?P<editingid>\d*)/(?P<mirnaid>\d*)/$', views.functionGainLoss,
        name='functiongainloss'),

    # rnafold
    url(r'^rnafold/(?P<lncrnaid>\d*)/(?P<editingid>\d*)/$', views.rnafold, name='rnafold'),

    #quick search
    url(r'^search/$', views.quickSearch, name='quicksearch'),
    # tools
    url(r'^tool/interaction/$', views.tInteraction, name='tinteraction'),
    url(r'^tool/structure/$', views.tStructure, name='tstructure')
]

human/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^editing/$', views.editing, name="editing"),
    url(r'^lncrna/$', views.lncrna, name="lncrna"),
    url(r'^mirna/$', views.mirna, name="mirna"),
    url(r'^download/$', views.download, name="download"),
    url(r'^help/$', views.help, name="help"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^queryset/(?P<page>\w*.*\w*)/$', views.getQuerySet, name="queryset"),

    #lncRNA details
    url(r'^lncrna/(?P<chrom>chr[1-9|XYM][0-9]?)/$', views.lncrnaChr, name="lncrnachr"),
    url(r'^lncrna/show/(?P<lncrnaid>\d*)/$', views.lncrnaShow, name="lncrnashow"),
    url(r'^lncrna/sequence/(?P<lncrnaid>\d*)/$', views.sequence, name='lncrnasequence'),
    url(r'^lncrna/structure/lncrnastructure_(?P<lncrnaid>\d*).png$', views.lncrnaStructure, name="lncrnastructure"),

    #Editing details
    url(r'^editing/show/(?P<editingid>\d*)/$', views.editingShow, name="editingshow"),


    #miRNA details
    url(r'^mirna/expression/$', views.mirnaExpression, name='mirnaexpression'),
    url(r'^mirna/show/(?P<mirnaid>\d*)/$', views.mirnaShow, name="mirnashow"),

    #funciton gain and loss
    url(r'^function/(?P<function>gain|loss)/(?P<editingid>\d*)/(?P<mirnaid>\d*)/$', views.functionGainLoss, name='functiongainloss'),

    #rnafold
    url(r'^rnafold/(?P<lncrnaid>\d*)/(?P<editingid>\d*)/$', views.rnafold, name='rnafold'),

    #quick search
    url(r'^search/$', views.quickSearch, name='quicksearch'),

    #tools
    url(r'^tool/interaction/$', views.tInteraction, name='tinteraction'),
    url(r'^tool/structure/$', views.tStructure, name='tstructure'),

]

lncRNAediting/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include("human.urls", namespace="human")),
    url(r'^mouse/', include("mouse.urls", namespace="mouse")),
    url(r'^fly/', include("fly.urls", namespace="fly")),
    url(r'^rhesus/', include("rhesus.urls", namespace="rhesus")),
    url(r'^admin/', admin.site.urls),
]

human/models.py
from django.db import models

# Create your models here.

class mirna_info(models.Model):
    mirna_id = models.CharField(max_length=225)
    accession = models.CharField(max_length=225)
    chromosome = models.CharField(max_length=45)
    strand = models.CharField(max_length=4)
    start = models.BigIntegerField()
    end = models.BigIntegerField()
    mature_sequence = models.CharField(max_length=500)
    pre_mirna_id = models.CharField(max_length=45)
    pre_start = models.BigIntegerField()
    pre_end = models.BigIntegerField()
    pre_sequence = models.CharField(max_length=10000)

    def __str__(self):
        return self.mirna_id

class lncrna_info(models.Model):
    lncrna_id = models.CharField(max_length=225,null=True)
    combined_resource = models.CharField(max_length=225,null=True)
    strand = models.CharField(max_length=4,null=True)
    annotation_by_RADAR = models.CharField(max_length=225,null=True)
    chromosome = models.CharField(max_length=45,null=True)
    trans_start = models.BigIntegerField(null=True)
    trans_end = models.BigIntegerField(null=True)
    exons_count = models.IntegerField(null=True)
    exons_start = models.TextField(null=True)
    exons_end = models.TextField(null=True)
    wild_sequence = models.TextField(null=True)
    wild_energy = models.FloatField(null=True)
    edit_sequence = models.TextField( null=True)
    edit_energy = models.FloatField(null=True)
    delta_energy = models.FloatField(null=True)
    edit_num = models.IntegerField(null=True)
    gain_num = models.IntegerField(null=True)
    loss_num = models.IntegerField(null=True)

    def __str__(self):
        return self.lncrna_id

class edit_site_info(models.Model):
    chromosome = models.CharField(max_length=45,null=True)
    chr_edit_pos = models.BigIntegerField(null=True)
    trans_edit_pos = models.BigIntegerField(null=True)
    lncrna_id = models.CharField(max_length=225,null=True)
    resource = models.CharField(max_length=225,null=True)
    lncrna_info = models.ForeignKey(lncrna_info)

    def __str__(self):
        return self.lncrna_id

class function_losses(models.Model):
    mirna_id = models.CharField(max_length=225,null=True)
    chromosome = models.CharField(max_length=20,null=True)
    chr_edit_pos = models.BigIntegerField(null=True)
    lncrna_id = models.CharField(max_length=225,null=True)
    resource = models.CharField(max_length=200,null=True)
    score = models.FloatField(null=True)
    energy = models.FloatField(null=True)
    targetscan_start_r = models.BigIntegerField(null=True)
    targetscan_end_r = models.BigIntegerField(null=True)
    miranda_start_r = models.BigIntegerField(null=True)
    miranda_end_r = models.BigIntegerField(null=True)
    ref_edit_pos = models.IntegerField(null=True)
    en = models.FloatField(null=True)
    query_start = models.IntegerField(null=True)
    query_end = models.IntegerField(null=True)
    ref_start = models.IntegerField(null=True)
    ref_end = models.IntegerField(null=True)
    align_length = models.IntegerField(null=True)
    query_percentage = models.FloatField(null=True)
    ref_percentage = models.FloatField(null=True)
    query_match_sequence = models.CharField(max_length=225,null=True)
    match_string = models.CharField(max_length=225, null=True)
    ref_match_sequence = models.CharField(max_length=225,null=True)
    edit_site_info = models.ForeignKey(edit_site_info)
    mirna_info = models.ForeignKey(mirna_info)

    def __str__(self):
        return self.mirna_id

class function_gains(models.Model):
    mirna_id = models.CharField(max_length=225,null=True)
    chromosome = models.CharField(max_length=20,null=True)
    chr_edit_pos = models.BigIntegerField(null=True)
    lncrna_id = models.CharField(max_length=225,null=True)
    resource = models.CharField(max_length=200,null=True)
    score = models.FloatField(null=True)
    energy = models.FloatField(null=True)
    targetscan_start_r = models.BigIntegerField(null=True)
    targetscan_end_r = models.BigIntegerField(null=True)
    miranda_start_r = models.BigIntegerField(null=True)
    miranda_end_r = models.BigIntegerField(null=True)
    ref_edit_pos = models.IntegerField(null=True)
    en = models.FloatField(null=True)
    query_start = models.IntegerField(null=True)
    query_end = models.IntegerField(null=True)
    ref_start = models.IntegerField(null=True)
    ref_end = models.IntegerField(null=True)
    align_length = models.IntegerField(null=True)
    query_percentage = models.FloatField(null=True)
    ref_percentage = models.FloatField(null=True)
    query_match_sequence = models.CharField(max_length=225,null=True)
    match_string = models.CharField(max_length=225, null=True)
    ref_match_sequence = models.CharField(max_length=225,null=True)
    edit_site_info = models.ForeignKey(edit_site_info)
    mirna_info = models.ForeignKey(mirna_info)

    def __str__(self):
        return self.mirna_id

class edit_sequence(models.Model):
    wild_sequence = models.TextField(null=True)
    wild_energy = models.FloatField(null=True)
    edit_squence = models.TextField(null=True)
    edit_energy = models.FloatField(null=True)
    delta_energy = models.FloatField(null=True)
    edit_site_info = models.ForeignKey(edit_site_info)

    def __str__(self):
        return  self.edit_energy

class resource(models.Model):
    lncrna_name = models.CharField(max_length=45,null=True)
    resource = models.CharField(max_length=45,null=True)
    description = models.TextField(null=True)
    link = models.TextField(null=True)
    lncrna_info = models.ForeignKey(lncrna_info)

    def __str__(self):
        return  self.lncrna_name

class mirna_profile(models.Model):
    mirna_id = models.CharField(max_length=45,null=True)
    acc = models.FloatField(null=True)
    blca = models.FloatField(null=True)
    brca = models.FloatField(null=True)
    cesc = models.FloatField(null=True)
    coad = models.FloatField(null=True)
    dlbc = models.FloatField(null=True)
    esca = models.FloatField(null=True)
    hnsc = models.FloatField(null=True)
    kich = models.FloatField(null=True)
    kirc = models.FloatField(null=True)
    kirp = models.FloatField(null=True)
    laml = models.FloatField(null=True)
    lgg = models.FloatField(null=True)
    lihc = models.FloatField(null=True)
    luad = models.FloatField(null=True)
    lusc = models.FloatField(null=True)
    meso = models.FloatField(null=True)
    ov = models.FloatField(null=True)
    paad = models.FloatField(null=True)
    pcpg = models.FloatField(null=True)
    prad = models.FloatField(null=True)
    reada = models.FloatField(null=True)
    sarc = models.FloatField(null=True)
    skcm = models.FloatField(null=True)
    stad = models.FloatField(null=True)
    thca = models.FloatField(null=True)
    ucec = models.FloatField(null=True)
    ucs = models.FloatField(null=True)
    mirna_info = models.OneToOneField(mirna_info)

    def __str__(self):
        return self.mirna_id

class repeat_conservation(models.Model):
    chromosome = models.CharField(max_length=45, null=True)
    chr_edit_pos = models.BigIntegerField()
    repeat = models.CharField(max_length=225, null=True)
    chimpanzee = models.CharField(max_length=225, null=True)
    rhesus = models.CharField(max_length=225, null=True)
    mouse = models.CharField(max_length=225, null=True)
    
    def __str__(self):
        return self.chromosome

human/forms.py
from django import forms

class QuickSearchForm(forms.Form):
    quick_search = forms.CharField(label="quick search", max_length=100)

human/templates/lncrna/chromosome_map.html
{% load staticfiles %}
{% load humanize %}
<div class="bs-docs-section">
    <div class="bs-callout bs-callout-info">
        <h4>lncRNA Transcripts</h4>
        <p>In this module, we provide the information of <span class="badge alert-info">40,229</span> human lncRNA transcripts. There are <span class="badge alert-danger">{{ total.count|intcomma }}</span> human lncRNAs on <span class="badge alert-success">{{ chromosome|default:"all chromosomes" }}.</span> </p>
        <form class="form-horizontal" role="form" method="get" action="{% url 'human:lncrna' %}">
            {% csrf_token %}
            <div class="form-group has-success" style="margin-top:20px;">
                <label class="control-label col-sm-2">Name or ID&nbsp;<span class="glyphicon glyphicon-question-sign" data-toggle="popover" data-content="Input lncRNA Name or  ID such as 'H19' or 'NONHSAT000088'" data-trigger="hover" data-placement="bottom"></span>:</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" name="term" value="{{ term|default:'H19' }}" placeholder="H19" pattern="[a-zA-Z0-9]*"/>
                </div>
                <div class="col-sm-2">
                    <button type="submit" class="btn btn-success">Search lncRNA</button>
                </div>

            </div>
        </form>
    </div>
    <div class="panel panel-default">
        <div class="panel-body">
            <img src="{% static 'human/images/chromosome.png' %}" alt="chromosome" usemap="chromosomemap">
            <map name="chromosomemap" id="chromosomemap">
                <area shape="rect" coords="21,115,31,135" href="{% url 'human:lncrnachr' 'chr1'%}" title="chr1"/>
                <area shape="rect" coords="58,115,68,135" href="{% url 'human:lncrnachr' 'chr2'%}" title="chr2"/>
                <area shape="rect" coords="99,115,109,135" href="{% url 'human:lncrnachr' 'chr3'%}" title="chr3"/>
                <area shape="rect" coords="136,115,146,135" href="{% url 'human:lncrnachr' 'chr4'%}" title="chr4"/>
                <area shape="rect" coords="174,115,184,135" href="{% url 'human:lncrnachr' 'chr5'%}" title="chr5"/>
                <area shape="rect" coords="213,115,223,135" href="{% url 'human:lncrnachr' 'chr6'%}" title="chr6"/>
                <area shape="rect" coords="253,115,263,135" href="{% url 'human:lncrnachr' 'chr7'%}" title="chr7"/>
                <area shape="rect" coords="289,115,300,135" href="{% url 'human:lncrnachr' 'chr8'%}" title="chr8"/>
                <area shape="rect" coords="326,115,337,135" href="{% url 'human:lncrnachr' 'chr9'%}" title="chr9"/>
                <area shape="rect" coords="362,115,380,135" href="{% url 'human:lncrnachr' 'chr10'%}" title="chr10"/>
                <area shape="rect" coords="399,115,418,135" href="{% url 'human:lncrnachr' 'chr11'%}" title="chr11"/>
                <area shape="rect" coords="438,115,456,135" href="{% url 'human:lncrnachr' 'chr12'%}" title="chr12"/>
                <area shape="rect" coords="479,115,496,135" href="{% url 'human:lncrnachr' 'chr13'%}" title="chr13"/>
                <area shape="rect" coords="518,115,533,135" href="{% url 'human:lncrnachr' 'chr14'%}" title="chr14"/>
                <area shape="rect" coords="556,115,573,135" href="{% url 'human:lncrnachr' 'chr15'%}" title="chr15"/>
                <area shape="rect" coords="596,115,613,135" href="{% url 'human:lncrnachr' 'chr16'%}" title="chr16"/>
                <area shape="rect" coords="633,115,648,135" href="{% url 'human:lncrnachr' 'chr17'%}" title="chr17"/>
                <area shape="rect" coords="669,115,687,135" href="{% url 'human:lncrnachr' 'chr18'%}" title="chr18"/>
                <area shape="rect" coords="709,115,727,135" href="{% url 'human:lncrnachr' 'chr19'%}" title="chr19"/>
                <area shape="rect" coords="744,115,763,135" href="{% url 'human:lncrnachr' 'chr20'%}" title="chr20"/>
                <area shape="rect" coords="781,115,800,135" href="{% url 'human:lncrnachr' 'chr21'%}" title="chr21"/>
                <area shape="rect" coords="820,115,838,135" href="{% url 'human:lncrnachr' 'chr22'%}" title="chr22"/>
                <area shape="rect" coords="862,115,875,135" href="{% url 'human:lncrnachr' 'chrX'%}" title="chrX"/>
                <area shape="rect" coords="901,115,915,135" href="{% url 'human:lncrnachr' 'chrY'%}" title="chrY"/>
                <area shape="rect" coords="21,0,31,105" href="{% url 'human:lncrnachr' 'chr1'%}" title="chr1"/>
                <area shape="rect" coords="58,3,68,105" href="{% url 'human:lncrnachr' 'chr2'%}" title="chr2"/>
                <area shape="rect" coords="99,22,109,105" href="{% url 'human:lncrnachr' 'chr3'%}" title="chr3"/>
                <area shape="rect" coords="136,27,146,105" href="{% url 'human:lncrnachr' 'chr4'%}" title="chr4"/>
                <area shape="rect" coords="174,28,184,105" href="{% url 'human:lncrnachr' 'chr5'%}" title="chr5"/>
                <area shape="rect" coords="213,33,223,105" href="{% url 'human:lncrnachr' 'chr6'%}" title="chr6"/>
                <area shape="rect" coords="253,38,263,105" href="{% url 'human:lncrnachr' 'chr7'%}" title="chr7"/>
                <area shape="rect" coords="290,46,300,105" href="{% url 'human:lncrnachr' 'chr8'%}" title="chr8"/>
                <area shape="rect" coords="327,48,337,105" href="{% url 'human:lncrnachr' 'chr9'%}" title="chr9"/>
                <area shape="rect" coords="366,48,376,105" href="{% url 'human:lncrnachr' 'chr10'%}" title="chr10"/>
                <area shape="rect" coords="403,48,414,105" href="{% url 'human:lncrnachr' 'chr11'%}" title="chr11"/>
                <area shape="rect" coords="442,50,452,105" href="{% url 'human:lncrnachr' 'chr12'%}" title="chr12"/>
                <area shape="rect" coords="482,54,493,105" href="{% url 'human:lncrnachr' 'chr13'%}" title="chr13"/>
                <area shape="rect" coords="520,55,530,105" href="{% url 'human:lncrnachr' 'chr14'%}" title="chr14"/>
                <area shape="rect" coords="557,55,567,105" href="{% url 'human:lncrnachr' 'chr15'%}" title="chr15"/>
                <area shape="rect" coords="596,63,610,105" href="{% url 'human:lncrnachr' 'chr16'%}" title="chr16"/>
                <area shape="rect" coords="633,64,645,105" href="{% url 'human:lncrnachr' 'chr17'%}" title="chr17"/>
                <area shape="rect" coords="671,65,684,105" href="{% url 'human:lncrnachr' 'chr18'%}" title="chr18"/>
                <area shape="rect" coords="709,70,724,105" href="{% url 'human:lncrnachr' 'chr19'%}" title="chr19"/>
                <area shape="rect" coords="747,73,760,105" href="{% url 'human:lncrnachr' 'chr20'%}" title="chr20"/>
                <area shape="rect" coords="783,75,797,105" href="{% url 'human:lncrnachr' 'chr21'%}" title="chr21"/>
                <area shape="rect" coords="822,74,837,105" href="{% url 'human:lncrnachr' 'chr22'%}" title="chr22"/>
                <area shape="rect" coords="861,38,874,105" href="{% url 'human:lncrnachr' 'chrX'%}" title="chrX"/>
                <area shape="rect" coords="901,73,913,105" href="{% url 'human:lncrnachr' 'chrY'%}" title="chrY"/>
            </map>
         </div>
     </div>
</div>

human/templates/lncrna/result_table.html
{% load humanize %}
{% if select %}
    <table class="table table-bordered table-hover table-condensed tablesorter tablesorter-bootstrap" role = "grid">
        <thead>
            <tr class = "active" role="row">
                <th width="20%">lncRNA ID</th>
                <th width="20%">Source</th>
                <th>Alias</th>
                <th>Chr</th>
                <th>Editing<br />Number</th>
                <th>Gain<span class="glyphicon glyphicon-question-sign" data-toggle="popover" data-content="The number of gain miRNA:lncRNA interactions on this lncRNA" data-trigger="hover" data-placement="bottom"></span></th>
                <th>Loss<span class="glyphicon glyphicon-question-sign" data-toggle="popover" data-content="The number of loss miRNA:lncRNA interactions on this lncRNA" data-trigger="hover" data-placement="bottom"></span></th>
            </tr>
        </thead>
        <tbody>
            {% for lncrna in select %}
            <tr>
                <td ><strong><a href="{% url 'human:lncrnashow' lncrna.id %}" class="lncrna-ID-{{ lncrna.id }}">{{ lncrna.lncrna_id }}</a></strong></td>
                <td class="resource-{{ lncrna.id  }}">{{ lncrna.combined_resource }}</td>
                <td>{{ lncrna.resource_set.all.0.resource|default:"-" }}</td>
                <td>{{ lncrna.chromosome }}</td>
                <td>{{ lncrna.edit_num }}</td>
                <td>{{ lncrna.gain_num|default:0 }}</td>
                <td>{{ lncrna.loss_num|default:0 }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

human/templates/lncrna/show.html
{% extends "human/base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    {% include 'lncrna/show/basic_information.html' %}
    {% include 'lncrna/show/lncrna_editing.html' %}
    {% include 'lncrna/show/lncrna_gain.html' %}
    {% include 'lncrna/show/lncrna_loss.html' %}
{% endblock %}