fly/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^editing/$', views.editing, name="editing"),
    url(r'^lncrna/$', views.lncrna, name="lncrna"),
    url(r'^mirna/$', views.mirna, name="mirna"),
    url(r'^download/$', views.download, name="download"),
    url(r'^help/$', views.help, name="help"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^queryset/(?P<page>\w*.*\w*)/$', views.getQuerySet, name="queryset"),

    #Editing details
    url(r'^editing/show/(?P<editingid>\d*)/$', views.editingShow, name="editingshow"),

    #lncRNA detail
    # url(r'^lncrna/(?P<chrom>chr[1-9|XYM][0-9]?)/$', views.lncrnaChr, name="lncrnachr"),
    url(r'^lncrna_chr/$', views.lncrnaChr, name="lncrnachr"),
    url(r'^lncrna/show/(?P<lncrnaid>\d*)/$', views.lncrnaShow, name="lncrnashow"),
    url(r'^lncrna/sequence/(?P<lncrnaid>\d*)/$', views.sequence, name='lncrnasequence'),
    url(r'^lncrna/structure/lncrnastructure_(?P<lncrnaid>\d*).png/$', views.lncrnaStructure, name="lncrnastructure"),

    # miRNA details
    url(r'^mirna/expression/$', views.mirnaExpression, name='mirnaexpression'),
    url(r'^mirna/show/(?P<mirnaid>\d*)/$', views.mirnaShow, name="mirnashow"),

    #funciton gain and loss
    # funciton gain and loss
    url(r'^function/(?P<function>gain|loss)/(?P<editingid>\d*)/(?P<mirnaid>\d*)/$', views.functionGainLoss,
        name='functiongainloss'),

    # rnafold
    url(r'^rnafold/(?P<lncrnaid>\d*)/(?P<editingid>\d*)/$', views.rnafold, name='rnafold'),

    #quick search
    url(r'^search/$', views.quickSearch, name='quicksearch'),
    # tools
    url(r'^tool/interaction/$', views.tInteraction, name='tinteraction'),
    url(r'^tool/structure/$', views.tStructure, name='tstructure')
]

lncRNAediting/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include("human.urls", namespace="human")),
    url(r'^mouse/', include("mouse.urls", namespace="mouse")),
    url(r'^fly/', include("fly.urls", namespace="fly")),
    url(r'^rhesus/', include("rhesus.urls", namespace="rhesus")),
    url(r'^admin/', admin.site.urls),
]

fly/models.py
from django.db import models

# Create your models here.

class mirna_info(models.Model):
    mirna_id = models.CharField(max_length=225)
    accession = models.CharField(max_length=225)
    chromosome = models.CharField(max_length=45)
    strand = models.CharField(max_length=4)
    start = models.BigIntegerField()
    end = models.BigIntegerField()
    mature_sequence = models.CharField(max_length=500)
    pre_mirna_id = models.CharField(max_length=45)
    pre_start = models.BigIntegerField()
    pre_end = models.BigIntegerField()
    pre_sequence = models.CharField(max_length=10000)

    def __str__(self):
        return self.mirna_id

class lncrna_info(models.Model):
    lncrna_id = models.CharField(max_length=225,null=True)
    combined_resource = models.CharField(max_length=225,null=True)
    strand = models.CharField(max_length=4,null=True)
    annotation_by_RADAR = models.CharField(max_length=225,null=True)
    chromosome = models.CharField(max_length=45,null=True)
    trans_start = models.BigIntegerField(null=True)
    trans_end = models.BigIntegerField(null=True)
    exons_count = models.IntegerField(null=True)
    exons_start = models.TextField(null=True)
    exons_end = models.TextField(null=True)
    wild_sequence = models.TextField(null=True)
    wild_energy = models.FloatField(null=True)
    edit_sequence = models.TextField( null=True)
    edit_energy = models.FloatField(null=True)
    delta_energy = models.FloatField(null=True)
    edit_num = models.IntegerField(null=True)
    gain_num = models.IntegerField(null=True)
    loss_num = models.IntegerField(null=True)

    def __str__(self):
        return self.lncrna_id

class edit_site_info(models.Model):
    chromosome = models.CharField(max_length=45,null=True)
    chr_edit_pos = models.BigIntegerField(null=True)
    trans_edit_pos = models.BigIntegerField(null=True)
    lncrna_id = models.CharField(max_length=225,null=True)
    resource = models.CharField(max_length=225,null=True)
    lncrna_info = models.ForeignKey(lncrna_info)

    def __str__(self):
        return self.lncrna_id

class function_losses(models.Model):
    mirna_id = models.CharField(max_length=225,null=True)
    chromosome = models.CharField(max_length=20,null=True)
    chr_edit_pos = models.BigIntegerField(null=True)
    lncrna_id = models.CharField(max_length=225,null=True)
    resource = models.CharField(max_length=200,null=True)
    score = models.FloatField(null=True)
    energy = models.FloatField(null=True)
    targetscan_start_r = models.BigIntegerField(null=True)
    targetscan_end_r = models.BigIntegerField(null=True)
    miranda_start_r = models.BigIntegerField(null=True)
    miranda_end_r = models.BigIntegerField(null=True)
    ref_edit_pos = models.IntegerField(null=True)
    en = models.FloatField(null=True)
    query_start = models.IntegerField(null=True)
    query_end = models.IntegerField(null=True)
    ref_start = models.IntegerField(null=True)
    ref_end = models.IntegerField(null=True)
    align_length = models.IntegerField(null=True)
    query_percentage = models.FloatField(null=True)
    ref_percentage = models.FloatField(null=True)
    query_match_sequence = models.CharField(max_length=225,null=True)
    match_string = models.CharField(max_length=225, null=True)
    ref_match_sequence = models.CharField(max_length=225,null=True)
    edit_site_info = models.ForeignKey(edit_site_info)
    mirna_info = models.ForeignKey(mirna_info)

    def __str__(self):
        return self.mirna_id

class function_gains(models.Model):
    mirna_id = models.CharField(max_length=225,null=True)
    chromosome = models.CharField(max_length=20,null=True)
    chr_edit_pos = models.BigIntegerField(null=True)
    lncrna_id = models.CharField(max_length=225,null=True)
    resource = models.CharField(max_length=200,null=True)
    score = models.FloatField(null=True)
    energy = models.FloatField(null=True)
    targetscan_start_r = models.BigIntegerField(null=True)
    targetscan_end_r = models.BigIntegerField(null=True)
    miranda_start_r = models.BigIntegerField(null=True)
    miranda_end_r = models.BigIntegerField(null=True)
    ref_edit_pos = models.IntegerField(null=True)
    en = models.FloatField(null=True)
    query_start = models.IntegerField(null=True)
    query_end = models.IntegerField(null=True)
    ref_start = models.IntegerField(null=True)
    ref_end = models.IntegerField(null=True)
    align_length = models.IntegerField(null=True)
    query_percentage = models.FloatField(null=True)
    ref_percentage = models.FloatField(null=True)
    query_match_sequence = models.CharField(max_length=225,null=True)
    match_string = models.CharField(max_length=225, null=True)
    ref_match_sequence = models.CharField(max_length=225,null=True)
    edit_site_info = models.ForeignKey(edit_site_info)
    mirna_info = models.ForeignKey(mirna_info)

    def __str__(self):
        return self.mirna_id

class edit_sequence(models.Model):
    wild_sequence = models.TextField(null=True)
    wild_energy = models.FloatField(null=True)
    edit_squence = models.TextField(null=True)
    edit_energy = models.FloatField(null=True)
    delta_energy = models.FloatField(null=True)
    edit_site_info = models.ForeignKey(edit_site_info)

    def __str__(self):
        return  self.edit_energy

class resource(models.Model):
    lncrna_name = models.CharField(max_length=45,null=True)
    resource = models.CharField(max_length=45,null=True)
    description = models.TextField(null=True)
    link = models.TextField(null=True)
    lncrna_info = models.ForeignKey(lncrna_info)

    def __str__(self):
        return  self.lncrna_name

class repeat_conservation(models.Model):
    chromosome = models.CharField(max_length=45, null=True)
    chr_edit_pos = models.BigIntegerField()
    repeat = models.CharField(max_length=45, null=True)
    
    def __str__(self):
        return self.chromosome

fly/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render_to_response,render
from django.template import RequestContext,loader
from django.http import Http404, HttpResponseRedirect, HttpResponse
from .functions import *
# Create your views here.
def index(request):
    title = "fly LNCediting"
    context = {"title":title}
    return render(request, 'fly/index.html', context)

def editing(request):
    title = "Fly Editing Site"
    # Form input
    csrfmiddlewaretoken =request.GET['csrfmiddlewaretoken']
    regex = re.compile('[#$%^&*()+=\[\]\';,\/{}|"<>?~\\\\]')
    if regex.search(csrfmiddlewaretoken):
        html = "<html><body>Input is illegal</body></html>"
        return HttpResponse(html)
    total = edit_site_info.objects.using("fly")
    if 'position' in request.GET:
        # position
        position = request.GET['position']

        regex = re.compile('[#$%^&*()+=\[\]\';,\/{}|"<>?~\\\\]')
        if regex.search(position):
            html = "<html><body>Input is illegal</body></html>"
            return HttpResponse(html)

        positionPattern = re.compile(r'[:-]')
        if positionPattern.search(position):
            positionSplit = positionPattern.split(position)
            if len(positionSplit) == 3:
                total = total.filter(chromosome__exact=positionSplit[0]).filter(
                    chr_edit_pos__gte=int(positionSplit[1])).filter(chr_edit_pos__lte=positionSplit[2])
            else:
                total = total.filter(chromosome__exact=positionSplit[0])
        elif position.startswith("chr"):
            total = total.filter(chromosome__exact=position)

        # source
    #     source = request.GET['source']
    #     if not source == "":
    #         total = total.filter(resource__contains=source)
    else:
        position = ""
    if 'term' in request.GET:
        term = request.GET['term']
        regex = re.compile('[#$%^&*()+=\[\]\';,\/{}|"<>?~\\\\]')
        if regex.search(term):
            html = "<html><body>Input is illegal</body></html>"
            return HttpResponse(html)
        total = total.filter(lncrna_id__icontains=term)
    pagination = paginate(request, total)
    select = total[pagination["offset"]: pagination["offsetEnd"]]

    context = {"total": total, "select": select, "title": title, "position": position, "pagination": pagination}
    return render(request, 'fly/editing.html', context)

def lncrna(request):
    title = "Fly lncRNA"
    total = lncrna_info.objects.using('fly')

    csrfmiddlewaretoken =request.GET['csrfmiddlewaretoken']
    regex = re.compile('[#$%^&*()+=\[\]\';,\/{}|"<>?~\\\\]')
    if regex.search(csrfmiddlewaretoken):
        html = "<html><body>Input is illegal</body></html>"
        return HttpResponse(html)

    if "term" in request.GET:
        term = request.GET.get('term')

        regex = re.compile('[#$%^&*()+=\[\]\';,\/{}|"<>?~\\\\]')
        if regex.search(term):
            html = "<html><body>Input is illegal</body></html>"
            return HttpResponse(html)

        total = total.filter(lncrna_id__icontains=term) | total.filter(resource__resource__icontains=term)
    pagination = paginate(request, total)
    select = total[pagination["offset"]: pagination["offsetEnd"]]
    context = {"title":title, "total":total, "select": select,"pagination": pagination}
    return render(request, 'fly/lncrna.html', context)

def mirna(request):
    title = "fly miRNA"
    total_temp = mirna_info.objects.using('fly')
    total = list()
    for i in total_temp:
        if i.function_gains_set.count() or i.function_losses_set.count():
            total.append(i)
    pagination = paginate(request, total)
    select = total[pagination["offset"]: pagination["offsetEnd"]]
    context = {"title": title, "total": total, "select": select, "pagination": pagination}
    return render(request, 'fly/mirna.html', context)

def download(request):

    return render(request, 'fly/download.html')

def help(request):

    return render(request, 'fly/help.html')

def contact(request):

    return render(request, 'fly/contact.html')

def getQuerySet(request, page):
    total=list()
    if page == "Fly Editing Site":
        total = edit_site_info.objects.using('fly')
    if page == "Fly lncRNA":
        total = lncrna_info.objects.using('fly')

    return HttpResponse(total, content_type='text/plain')


def editingShow(request, editingid):
    title = "Rhesus Editing Site"
    editingRecord = edit_site_info.objects.using('fly').get(pk=editingid)
    editingLncrna = lncrna_info.objects.using('fly').get(pk=editingRecord.lncrna_info_id)
    editingEach = edit_sequence.objects.using('fly').get(edit_site_info_id__exact=editingid)

    rep_cons = repeat_conservation.objects.using("fly").filter(chromosome__exact=editingRecord.chromosome).filter(chr_edit_pos__exact=editingRecord.chr_edit_pos).first()

    editingGain = None
    editingLoss = None
    try:
        editingGain = function_gains.objects.using('fly').filter(edit_site_info_id=editingid)
    except:
        pass
    try:
        editingLoss = function_losses.objects.using('fly').filter(edit_site_info_id=editingid)
    except:
        pass

    context = {"title": title, "editingid": editingid, "editingRecord": editingRecord, "editingLncrna": editingLncrna,"editingGain": editingGain, "editingLoss": editingLoss, "editingEach": editingEach, "rep_cons":rep_cons}
    return render(request, 'fly_editing/show.html', context)

def lncrnaChr(request):
    csrfmiddlewaretoken =request.GET['csrfmiddlewaretoken']
    regex = re.compile('[#$%^&*()+=\[\]\';,\/{}|"<>?~\\\\]')
    if regex.search(csrfmiddlewaretoken):
        html = "<html><body>Input is illegal</body></html>"
        return HttpResponse(html)
    chrom = request.GET.get("chromosome", "all_chromosome")
    if regex.search(chrom):
        html = "<html><body>Input is illegal</body></html>"
        return HttpResponse(html)
    title = "fly lncRNA"
    total = lncrna_info.objects.using('fly')
    if chrom != "all_chromosome":
        total = total.filter(chromosome__exact = chrom)
    pagination = paginate(request, total)
    select = total[pagination["offset"]: pagination["offsetEnd"]]

    context = {"title": title, "total": total, "select": select,"chromosome":chrom, "pagination": pagination}
    return render(request, 'fly/lncrna.html', context)

def lncrnaShow(request, lncrnaid):
    title = "fly lncRNA"
    lncrnaRecord = lncrna_info.objects.using('fly').get(pk=lncrnaid)
    lncrnaEditing = edit_site_info.objects.using('fly').filter(lncrna_info_id__exact=lncrnaRecord.id)
    lncrnaGain = list()
    lncrnaLoss = list()
    for edit in lncrnaEditing:
        try:
            lncrnaGain.extend(function_gains.objects.using('fly').filter(edit_site_info_id=edit.id))
        except:
            continue
    for edit in lncrnaEditing:
        try:
            lncrnaLoss.extend(function_losses.objects.using('fly').filter(edit_site_info_id=edit.id))
        except:
            continue

    context = {"title": title, "lncrnaid": lncrnaid, "lncrnaRecord": lncrnaRecord, "lncrnaEditing": lncrnaEditing,
               "lncrnaGain": lncrnaGain, "lncrnaLoss": lncrnaLoss}
    return render(request, 'fly_lncrna/show.html', context)

def mirnaExpression(request):
    title = "fly miRNA"
    mirnaid = request.GET['mirna']

    mirnaInfo = mirna_info.objects.using('fly').get(pk=mirnaid)
    mirnaProfile = mirna_profile.objects.using('fly').get(mirna_info_id__exact=mirnaid)
    mirnaGain = function_gains.objects.using('fly').filter(mirna_info_id__exact=mirnaid)
    mirnaLoss = function_losses.objects.using('fly').filter(mirna_info_id__exact=mirnaid)

    context = {"title":title,"mirnaid":mirnaid, "mirnaInfo":mirnaInfo, "mirnaProfile":mirnaProfile, "mirnaGain":mirnaGain, "mirnaLoss":mirnaLoss}
    return render(request, 'fly_mirna/show.html', context)

def mirnaShow(request, mirnaid):
    title = "fly miRNA"


    mirnaInfo = mirna_info.objects.using('fly').get(pk=mirnaid)
    try:
        mirnaProfile = mirna_profile.objects.using('fly').get(mirna_info_id__exact=mirnaid)
    except:
        mirnaProfile=""
    mirnaGain = function_gains.objects.using('fly').filter(mirna_info_id__exact=mirnaid)
    mirnaLoss = function_losses.objects.using('fly').filter(mirna_info_id__exact=mirnaid)

    context = {"title": title, "mirnaid": mirnaid, "mirnaInfo": mirnaInfo, "mirnaProfile": mirnaProfile,
               "mirnaGain": mirnaGain, "mirnaLoss": mirnaLoss}
    return render(request, 'fly_mirna/show.html', context)

fly/templates/fly_editing/result_table.html
{% load humanize %}
{% if select %}
    <table class="table table-bordered table-hover table-condensed tablesorter tablesorter-bootstrap" role = "grid">
        <thead>
            <tr class = "active" role="row">
                <th>Editing Position</th>
                <th>Transcript Edit Position</th>
                <th>lncRNA ID</th>
                <th>Source</th>
            </tr>
        </thead>
        <tbody>
            {% for edit in select %}
            <tr>
                <td><a href = "{% url 'fly:editingshow' edit.id %}">{{ edit.chromosome }}:{{ edit.chr_edit_pos|intcomma }}</a></td>
                <td>{{ edit.trans_edit_pos|intcomma }}</td>
                <td><a href="{% url 'fly:lncrnashow' edit.lncrna_info_id %}" id = "lncrna-ID-{{ edit.lncrna_info_id }}">{{ edit.lncrna_id }}</a></td>
                <td id="resource-{{ edit.lncrna_info_id  }}">{{ edit.resource }}</td>
            </tr>
            <script type="text/javascript">
                $(function(){
                    var lncrnaID = '{{ edit.lncrna_id }}';
                    var source = '{{ edit.resource }}';
                    var lncrnaIDs = lncrnaID.split("/");
                    var sources = source.split("/");
                    $("#lncrna-ID-{{ edit.lncrna_info_id  }}").text(lncrnaIDs[0]);
                    $("#resource-{{ edit.lncrna_info_id  }}").text(sources[0]);
                });
            </script>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

fly/templates/fly_editing/search_form.html
{% load humanize %}
<div class="bs-callout bs-callout-info">
    <div class="description">
    <h4>RNA editing in fly lncRNA transcripts.</h4>
    <p>In total, we identified <span class="badge alert-info">1,829</span> RNA editing sites in <span class="badge alert-success">11,089</span> fly lncRNA transcripts. Here, we develop an advanced search helping users to prioritize the functional RNA editing sites. Users can input chromosome IDs or chromosome region.</p>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" role="form" method="get" action="{% url 'fly:editing' %}">
            {% csrf_token %}
            <div class="form-group has-success">
                <label class="control-label col-sm-2">Position:</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" name="position" value="{{ position }}" placeholder="chr2L:1102563-201688733" pattern="chr.*:\d*-\d*"/>
                </div>
                <span class="help-block">Input a user-defined region such as "chr2L:1102563-201688733" or "chr2L"</span>
            </div>
            <div class="form-group has-success">
            <label class="control-label col-sm-2">lncRNA ID:</label>
            <div class="col-sm-3">
                <input type="text" class="form-control" name="term" value="{{ term }}" placeholder="NONDMEG000970.1" pattern="[a-zA-Z0-9\-\.]*"/>
            </div>
            <span class="help-block">Input lncRNA  ID such as "NONDMEG000970.1"</span>
            </div>
            <div class="form-group has-error">
                <div class="col-sm-offset-5 col-sm-2">
                    <button type="submit" class="btn btn-success">Search</button>
                    <button type="reset" class="btn btn-success">Reset</button>
                </div>
            </div>
        </form>
    </div>
</div>

fly/templates/fly_editing/show.html
{% extends "fly/base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    {% include 'fly_editing/show/basic_information.html' %}
    {% include 'fly_editing/show/editing_lncrna.html' %}
    {% include 'fly_editing/show/editing_gain.html' %}
    {% include 'fly_editing/show/editing_loss.html' %}
	{% if not editingGain and not editingLoss %}
	<div class="bs-docs-section">
		<div id="message" class="alert alert-success" role="alert">
			<button type="button" class="close" data-dismiss="alert"><span>x</span></button>
			<p>This editing site does not impact miRNA:lncRNA interaction by our prediction.</p>
		</div>
	</div>
	{% endif %}
{% endblock %}